### ISSUE TITLE
Propose sem-ver mechanism for dNation helm chart projects

### ISSUE THREAD

**Issue by matofeder** [dNationCloud/kubernetes-monitoring-stack#12]
- Investigate well know helm chart project like [prometheus](https://github.com/prometheus-community/helm-charts/tree/main/charts) or [grafana](https://github.com/grafana/helm-charts/tree/main/charts)

**Comment by davidsuba** [comment]
Proposed mechanism:
https://git.ifne.eu/infra/maintenance/-/wikis/GitHub
