### ISSUE TITLE
Add external grafana setup for using dnation

### ISSUE THREAD

**Issue by leegin** [dNationCloud/kubernetes-monitoring-stack#34]
We are using dNation Kubernetes monitoring stack and it is a useful tool for getting so many ready-made dashboards. We have a Prometheus setup which is controlled by the Prometheus Operator. When we install dNation stack in this cluster it is picking up the grafana in this setup. We are unable to find where we should add a custom grafana source for getting these dashboards. Can you guys please help us with this? This external grafana is running in VMs and we are planning to use them.

**Comment by matofeder** [comment]
Hi @leegin 

Happy to see that you use dNation Kubernetes Monitoring. Please let us know where you found a reference to our project. 
Regarding your issue:
dNation Kubernetes Monitoring stack deploys whole stack, it means Grafana, Prometheus Operator, Loki and dNation Monitoring. 
So, if you want to use external Grafana, running outside the kubernetes you need to import rendered  `dNation Grafana Dashboards` into it. 
Plese see following step by step instructions:
1. checkout https://github.com/dNationCloud/kubernetes-monitoring
2. run `make json-dashboards` 
    - Command above renders  `dNation Grafana Dashboards` to the  `json` directory
3. Then, you have to just import rendered dashboards into your external Grafana e.g. see https://grafana.com/docs/grafana/latest/http_api/dashboard/

**Comment by leegin** [comment]
@matofeder We found about dNation Kubernetes Monitoring from your medium [blog](https://matej-feder.medium.com/how-we-monitor-our-kubernetes-using-dnation-monitoring-eccff1728002). We were facing the same issue with spending so much time on customizing dashboards. The dNation monitoring is really useful for us now and it immensely helps in debugging. Thanks to you and your team for this awesome tool.

**Comment by matofeder** [comment]
@leegin Thanks for your feedback! We appreciate that. Can we use your motivating words in our [website](https://dnation.cloud/)?

**Comment by leegin** [comment]
@matofeder yes, please.
