### ISSUE TITLE
Add ci actions to test monitoring installation in latest k8s [releases](https://kubernetes.io/releases/)

### ISSUE THREAD

**Issue by matofeder** [dNationCloud/kubernetes-monitoring-stack#35]

**Comment by davidsuba** [comment]
See [same issue](https://github.com/dNationCloud/kubernetes-monitoring/issues/130) in kubernetes-monitoring.

**Comment by davidsuba** [comment]
Because it is time demanding action it shouldn't run on every PR but e.g. once in a month.
Test with k8s version 1.22.
