### ISSUE TITLE
Investigate Kubernetes Monitoring Alertmanager Time Zone setting

### ISSUE THREAD

**Issue by matofeder** [dNationCloud/kubernetes-monitoring-stack#9]
Investigate Kubernetes Monitoring Alertmanager TimeZone setting and pair triggered alerts with appropriate logs. 
e.g.:
1. Alert arrives at `8:03 AM CET`
![image](https://user-images.githubusercontent.com/17620218/104709785-9a581a80-571f-11eb-8669-b6226a643c04.png)
2. [Container detail view](https://k8s-h-01-monitoring.dnation.cloud/d/containerdetail/container-detail?orgId=1&var-datasource=k8s-h-01-metrics&var-datasource_logs=k8s-h-01-logs&var-view=container&var-cluster=&var-instance=All&var-namespace=All&var-pod=All&var-container=etcd&var-search=&from=1609923600000&to=1609923900000)
![image (1)](https://user-images.githubusercontent.com/17620218/104709800-9deba180-571f-11eb-88d9-444d15684300.png)
and  [Logs explorer](https://k8s-h-01-monitoring.dnation.cloud/explore?orgId=1&left=%5B%22now-7d%22,%22now%22,%22k8s-h-01-logs%22,%7B%22expr%22:%22%7Bnamespace%3D%5C%22kube-system%5C%22,%20stream%3D%5C%22stderr%5C%22%7D%20%7C~%20%5C%22(%3Fi)error%5C%22%20!~%20%5C%22Final%20error%20received,%20removing%20PVC%20.%2B%20from%20claims%20in%20progress%5C%22%22%7D,%7B%22mode%22:%22Logs%22%7D,%7B%22ui%22:%5Btrue,true,true,%22numbers%22%5D%7D%5D) 
![image (2)](https://user-images.githubusercontent.com/17620218/104709828-a643dc80-571f-11eb-9e72-43cac1bd9ae6.png)
 shows `9:03 AM CET` 

Consider that alert manager waits 5min before sending a notification about new alerts.

**Comment by davidsuba** [comment]
Timezones inside cluster (Alertmanager, Prometheus..) are consistently set to UTC. 
Time in mattermost and grafana is set to browser time.

In example above is alert probably paired with wrong log. (can't investigate further, because logs have been already deleted)

**Comment by davidsuba** [comment]
Investigating same error `etcdHighNumberOfFailedGRPCRequests` on `01-20-2021`: 

1.Alerts arrived at `13:32` and `13:55 CET` 
![image](https://user-images.githubusercontent.com/72123207/105188865-a0d9fe00-5b34-11eb-835b-b4940b321c62.png)

2. Count of logs for `etcd` container in range `12:00 - 15:00 CET`
![image](https://user-images.githubusercontent.com/72123207/105189735-8f452600-5b35-11eb-8d41-1aa786e6cb1f.png)
Errors and therefore increased amount of logs occured at the same time (+- delay of alertmanager) as alerts came.

Small part of logs from `etcd` during duration of second error:
![times](https://user-images.githubusercontent.com/72123207/105192097-10052180-5b38-11eb-9daf-9fc30581c798.jpg)

Conclusion:
Alerts and and appropriate logs timezone matches.
